version: "3.7"

networks:
  tmdb:
    driver: bridge

services:
  tmdb-api:
    container_name: tmdb-api
    build:
      context: .
    env_file:
      - .env
    networks:
      - tmdb
    ports:
      - '3000:3000'
    restart: on-failure
