export const TARGET_PERSONS: string[]  = [
  'Robert Downey Jr.',
  'Chris Evans',
  'Mark Ruffalo',
  'Chris Hemsworth',
  'Scarlett Johansson',
  'Jeremy Renner',
  'Don Cheadle',
  'Paul Rudd',
  'Brie Larson',
  'Michael B. Jordan',
  'Karen Gillan',
  'Danai Gurira',
  'Josh Brolin',
  'Gwyneth Paltrow',
  'Bradley Cooper',
  'Tom Holland',
  'Zoe Saldana',
  'Anthony Mackie',
  'Tom Hiddleston',
  'Chris Pratt',
  'Black Panther',
  'Samuel L. Jackson',
  'Dave Bautista'
];
